export enum SectorCode {
  CORTE = 'CORTE',
  BORDADO = 'BORDADO',
  ESTAMPADO = 'ESTAMPADO',
  AVIOS_CONFECCION = 'AVIOS_CONFECCION',
  CONFECCION = 'CONFECCION',
  ATRAQUE = 'ATRAQUE',
  OJAL_BOTON = 'OJAL_BOTON',
  AVIOS_TERMINACION = 'AVIOS_TERMINACION',
  PLANCHA = 'PLANCHA',
  TERMINACION = 'TERMINACION',
}

export enum StageExecutionType {
  INTERNO = 'INTERNO',
  EXTERNO = 'EXTERNO',
  AMBOS = 'AMBOS',
}

export enum SizeSequenceType {
  ALFABETICA = 'ALFABETICA',
  NUMERICA = 'NUMERICA',
  DOBLE = 'DOBLE',
}

export enum SupplyCategory {
  CONFECCION = 'CONFECCION',
  TERMINACION = 'TERMINACION',
}
