export enum NotificationType {
  INGRESO_ORDEN = 'INGRESO_ORDEN',
  FINALIZACION_ORDEN = 'FINALIZACION_ORDEN',
  FECHA_ESTIMADA_INCUMPLIDA = 'FECHA_ESTIMADA_INCUMPLIDA',
  CUELLO_DE_BOTELLA = 'CUELLO_DE_BOTELLA',
  ORDEN_EN_ARREGLO = 'ORDEN_EN_ARREGLO',
}
